kind: Workflow
metadata:
  name: big-search
  namespace: argo
spec:
  entrypoint: workflow-entrypoint
  podGC:
    strategy: OnWorkflowSuccess
    deleteDelayDuration: 600s
  parallelism: 1
  podMetadata:
    labels:
      app: coastlines
    annotations:
      karpenter.sh/do-not-disrupt: "true"
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  templates:
  - name: workflow-entrypoint
    container:
      image:  "ghcr.io/digitalearthpacific/dep-coastlines:v0.8.0dev41"
      imagePullPolicy: IfNotPresent
      resources:
        requests: 
          memory: 4Gi
          cpu: 2
      command: [ python ]
      args:
        - -c
        - "import dask; print(dask.config.config)"
